### PR TITLE
Add python pkg structure + add automated CI testing pipeline + add Coverage report

### PR DESCRIPTION
**Pull request by navidcy**
This PR converts the repo towards a python package! Also, the PR adds a testing CI pipeline and a Coverage report via Codecov.io. This is the first step towards #12, but it doesn't resolve it since the test include here are just placeholder (e.g., they are trivialities, like test whether `4**2 == 16`).

### CODE REVIEW

**Comment by navidcy** [comment]
#12 should be addressed here -- at least the CI pipeline should be created :)

**Comment by navidcy** [comment]
@angus-g is this error
https://github.com/COSIMA/mom6-regional-scripts/actions/runs/5153002229/jobs/9279708416?pr=26#step:4:190
related with your git commit comment here:
https://github.com/COSIMA/mom6-regional-scripts/commit/fc00d4ac93a7a16f062d2de7f5055a8ce7a29b9b
?

**Comment by navidcy** [comment]
@ashjbarnes mentioned that some of the dependencies need to be installed via conda.

Would something like this
https://github.com/mwouts/jupytext/blob/64b84b7402c9c637372eb2ea7c98b6471651c38e/.github/workflows/continuous-integration.yml#L130-L177
be a better CI pipeline?

**Comment by navidcy** [comment]
https://github.com/COSIMA/mom6-regional/actions/runs/5196044606/jobs/9369359484#step:4:314

are you sure the package is called `pangeo-xesmf`? is this name from pip installation but `xesmf` when installing via conda?

**Comment by navidcy** [comment]
OK, I think I made the CI reach the point where it actually wants to run the tests... but the `pytest` call fails (probably because of the directory structure of the package?)

**Comment by navidcy** [comment]
OK, the test pipeline works! 

@angus-g did I do it correctly? Any ideas, suggestions are welcome!

**Comment by angus-g** [comment]
> are you sure the package is called `pangeo-xesmf`

It was called that when I made that commit -- it was at a time when they transitioned it into the pangeo organisation, but didn't have control of the xesmf name on PyPI. I guess now they've moved back to just plain old xesmf so that's fine.

> @angus-g did I do it correctly? Any ideas, suggestions are welcome!

I'll have a look today.

**Comment by angus-g** [comment]
I've made some adaptations in the [`angus-g/pyproject`](https://github.com/COSIMA/mom6-regional/tree/angus-g/pyproject) branch, are you happy for them to merge into this PR branch?

**Comment by navidcy** [comment]
merge anything! commit to this branch!

**Comment by navidcy** [comment]
OK, so now all the contents of [regional_library.py](https://github.com/COSIMA/mom6-regional/blob/ncc/convert-to-pkg/regional_library.py) should move into `mom6_regional/mom6_regional.py`?

**Comment by angus-g** [comment]
Yeah, I think that's a good next step.

**Comment by navidcy** [comment]
also, what's the difference of `regional_library.py` and `[regional_model_scripts.py](https://github.com/COSIMA/mom6-regional/blob/ncc/convert-to-pkg/regional_model_scripts.py)`?

**Comment by angus-g** [comment]
Just as functions is fine, if you provide them in `__all__` then they'll be accessible as `mom6_regional.whatever_function()`.

I think the "scripts" version is the externally-driven workflow -- you call things in the right order and it works on the files from the previous step to give you the next step. The "library" is meant to be internally-consistent, I believe.

**Comment by navidcy** [comment]
classes can also be included in `__all__`?

**Comment by navidcy** [comment]
Also, formatting fails. What do I do for that? (Like, I can go ahead and edit the file line-by-line but I'm asking if there is a better/more sane way for doing this.)

**Comment by angus-g** [comment]
Install and run `black`

**Comment by navidcy** [comment]
OK another question (sorry!)

If I want to reproduce the tests locally (including the creation of the env etc...) what's the workflow?

```
conda create --name mom6-regional-ci --file environment-ci.yml
python -m pip install .
python -m pip install pytest
```
?

The first line fails....

```
$ conda create --name mom6-regional-ci --file environment-ci.yml

CondaValueError: could not parse 'name: mom6-regional-dev' in: environment-ci.yml
```

**Comment by navidcy** [comment]
Also, do we need both `environment.yml` and `requirements.txt`?

**Comment by navidcy** [comment]
OK, moving everything into `mom6_regional/mom6_regional.py` broke the CI
I presume it's something to do with dependencies not being properly installed and possibly it boils down to the fact that I don't know what `requirements.txt` and what `environment.yml` do. Intuitively I'd think that we only want one thing to describe the pkg dependencies, right? Or if we need both (eg for `pip` or `conda` installations then they should include the same deps?

**Comment by navidcy** [comment]
Also what's this hint about? https://github.com/COSIMA/mom6-regional/actions/runs/5253112064/jobs/9490028654?pr=26#step:5:16

**Comment by navidcy** [comment]
> Also what's this hint about? https://github.com/COSIMA/mom6-regional/actions/runs/5253112064/jobs/9490028654?pr=26#step:5:16

This is gone now :)

**Comment by angus-g** [comment]
> If I want to reproduce the tests locally (including the creation of the env etc...) what's the workflow?

I think your command just needs to be `conda env create -f environment-ci.yml`, but I think you also need to specify a Python version to get it to resolve properly or something (just hanging for me)... I'm not particularly a Conda expert to be honest!

**Comment by navidcy** [comment]
Gotcha. I'll ask chatgpt!

**Comment by navidcy** [comment]
OK, I added code coverage report also!

**Review by ashjbarnes — APPROVED** [review]
Awesome thanks Navid and Angus!!

**Comment by angus-g** [comment]
No problem, I just haven't looked at any of the new stuff yet!

**Comment by navidcy** [comment]
@angus-g do that!

also @ashjbarnes it’s good practice to leave the person who open the review to merge.

**Comment by ashjbarnes** [comment]
Yes that makes sense! Will do in future

**Pull request merged**
